### ISSUE TITLE
关于某jwt的通信生成来源的疑问

### ISSUE THREAD

**Issue by WhZzi** [Hanxven/League-Stalker#1]
我目前将客户端本身的127.0.0.1:{PORT}接口视为一个转发工具，通过抓包劫持流量我目前看到，对某个接口发送请求时，实际上是做了如下转发：
本地请求接口：https://127.0.0.1:1641/lol-summoner/v1/check-name-availability-new-summoners/Xxxxxx
实际上是对此接口做出了转发请求 [[SPECIAL_HOST]]/summoner-ledge/v1/regions/**/validatename?summonerName=Xxxxxx
后面这个请求在请求过程中是携带了某个jwt,他的来源应该也是基于某个接口返回的,但是目前没有找到相关来源，不知道您是否对这个有研究，跟您求求解。
另外方便提供一下您的联系方式吗？

**Comment by Hanxven** [comment]
因为当前只需要和 League Client 客户端通信，我目前并没有涉及到 JWT 相关的内容。

不过关于 JWT，我倒是在接口中经常看到，虽然从来没有使用它们。JWT 包含在 LCU 的定期推送中，推测是只有较短的有效时间。

LCU 提供的其中一个接口：

`GET /lol-summoner/v1/current-summoner/jwt`

可以获得一个 JWT 字符串。不知这个是否是您所需要的？这需要您**登录英雄联盟客户端**。

**至于如何在不登陆游戏客户端的情况下获取 JWT Token，我并没有头绪，这超出了我目前的能力。**

> 关于 LCU 接口的相关信息，在 [样例](https://github.com/Hanxven/League-Stalker/tree/main/example/lcu-api/) 中可以导入到 Postman 接口集合。附带密钥和端口的命令行可以通过 WMIC 工具获得。（这需要管理员权限）

**Comment by WhZzi** [comment]
"GET /lol-summoner/v1/current-summoner/jwt" 这个接口请求的jwt是所需要的目标jwt,但是它基于已经打开的英雄联盟客户端，我在研究jwt的通信生成来源，但是貌似请求具有ssl-pinning，因此无法直接抓包解析流量来分析生成方式。

非常感谢您的耐心回复！您的工具很好用，再次致谢！
